<?php

namespace AppBundle\Repository\Ez;

/**
 * UrlContentLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlContentLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
