AppBundle\Entity\Ez\Url:
    type: entity
    table: ezurl
    repositoryClass: AppBundle\Repository\Ez\UrlRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        created:
            type: integer
        isValid:
            type: boolean
            column: is_valid
        lastChecked:
            type: integer
            column: last_checked
        modified:
            type: integer
        originalUrlMd5:
            type: string
            length: '32'
            column: original_url_md5
        url:
            type: text
    oneToMany:
        contentLinks:
            targetEntity: UrlContentLink
            mappedBy: url
    lifecycleCallbacks: {  }
