AppBundle\Entity\Ez\UrlContentLink:
    type: entity
    table: ezurl_object_link
    repositoryClass: AppBundle\Repository\Ez\UrlContentLinkRepository
    id:
        urlId:
            type: integer
            column: url_id
            id: true
        contentFieldId:
            type: integer
            column: contentobject_attribute_id
            id: true
        contentFieldVersion:
            type: integer
            column: contentobject_attribute_version
            id: true
    manyToOne:
        url:
            targetEntity: Url
            inversedBy: contentLinks
            joinColumn:
                name: url_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
